name: snakemake_read_vcf

channels:
  - bioconda
  - conda-forge
  

dependencies:
  - bioconda::snakemake-minimal =5.11.2
  - python =3.7
  - samtools =1.9
  - bwa =0.7.17
  - graphviz =2.38.0
  - gatk4 =4.1.5.0

